[34m[1mwandb[0m:   3 of 3 files downloaded.  
[34m[1mwandb[0m:   3 of 3 files downloaded.  
C:\Users\abia0\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
==== Resultados - Valida√ß√£o ====
Acur√°cia: 0.8167
              precision    recall  f1-score   support

           0       0.91      0.70      0.79        30
           1       0.76      0.93      0.84        30

    accuracy                           0.82        60
   macro avg       0.83      0.82      0.81        60
weighted avg       0.83      0.82      0.81        60


==== Resultados - Teste ====
Acur√°cia: 0.5167
              precision    recall  f1-score   support

           0       1.00      0.03      0.06        30
           1       0.51      1.00      0.67        30

    accuracy                           0.52        60
   macro avg       0.75      0.52      0.37        60
weighted avg       0.75      0.52      0.37        60
[34m[1mwandb[0m:   3 of 3 files downloaded.  

Final metrics logged.
Traceback (most recent call last):
  File "C:\Users\abia0\OneDrive\√Årea de Trabalho\Projetos\Faculdade\topicos_especiais\Effective-MLops\train.py", line 157, in <module>
    train_model(train_config)
  File "C:\Users\abia0\OneDrive\√Årea de Trabalho\Projetos\Faculdade\topicos_especiais\Effective-MLops\train.py", line 151, in train_model
    wandb.save('train.py')
  File "C:\Users\abia0\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 403, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abia0\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abia0\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2024, in save
    return self._save(
           ^^^^^^^^^^^
  File "C:\Users\abia0\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_run.py", line 2088, in _save
    target_path.symlink_to(source_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] O cliente n√£o tem o privil√©gio necess√°rio: 'C:\\Users\\abia0\\OneDrive\\√Årea de Trabalho\\Projetos\\Faculdade\\topicos_especiais\\Effective-MLops\\train.py' -> 'C:\\Users\\abia0\\OneDrive\\√Årea de Trabalho\\Projetos\\Faculdade\\topicos_especiais\\Effective-MLops\\wandb\\run-20241207_203949-2qexfom0\\files\\train.py'
